table 'Merchant Sentiment Distribution'
	lineageTag: 63800472-9f01-4b07-96f4-4392e0980004

	column merchant
		dataType: string
		lineageTag: 5ab54758-a536-4497-acf6-67466d0f1c3c
		summarizeBy: none
		sourceColumn: merchant

		annotation SummarizationSetBy = Automatic

	column sentiment
		dataType: string
		lineageTag: 28ac6fa3-ee3e-4409-95d1-53475e7d3c84
		summarizeBy: none
		sourceColumn: sentiment

		annotation SummarizationSetBy = Automatic

	column review_count
		dataType: int64
		formatString: 0
		lineageTag: 8ad4ca84-5798-4336-a8ed-8ea313df1493
		summarizeBy: sum
		sourceColumn: review_count

		annotation SummarizationSetBy = Automatic

	partition 'Merchant Sentiment Distribution' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\mason\PycharmProjects\SpokesfanMerchantAnalytics\data\processed\dashboard_metrics\merchant_sentiment_distribution.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"merchant", type text}, {"sentiment", type text}, {"review_count", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

